version: '4.33.1'

services:
  app:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:122221enochCodes@db:5432/syncory_db
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 122221enochCodes
      POSTGRES_DB: syncory_db

volumes:
  db-data:
