# Generated by Django 5.1 on 2024-08-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_attendee_id_attendee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='id',
            new_name='user_id',
        ),
    ]
